
# https://github.com/natemcmaster/dotnet-tools

# https://github.com/korzh/aistdoc
dotnet tool install -g Aistant.DocImport
# https://github.com/peacecwz/azure-storage-cli
dotnet tool install -g azure-storage-cli
# https://github.com/StevenThuriot/GitAutoCommit
dotnet tool install -g dotnet-autocommit
# https://github.com/korzh/aistdoc
dotnet tool install -g azuresigntool
# https://github.com/tonerdo/coverlet
dotnet tool install -g coverlet.console

# https://github.com/mirsaeedi/dotnet-apim A cross-platform dotnet tool which streamlines the CI/CD process of deploying APIs into Azure API Management
dotnet tool install -g Apim.DevOps.Toolkit
# https://github.com/aspnet/Scaffolding 
dotnet tool install -g dotnet-aspnet-codegenerator
# https://github.com/cake-build/cake
dotnet tool install -g Cake.Tool
# https://github.com/AdrianWilczynski/CSharpToTypeScript Convert C# Models, ViewModels and DTOs into their TypeScript equivalents.
dotnet tool install -g CSharpToTypeScript.CLITool
# https://github.com/aws/aws-extensions-for-dotnet-cli
dotnet tool install -g Amazon.ElasticBeanstalk.Tools
dotnet tool install -g Amazon.ECS.Tools
dotnet tool install -g Amazon.Lambda.Tools
# https://github.com/dotnet/format
dotnet tool install -g dotnet-format
# https://github.com/GitTools/GitVersion
dotnet tool install -g GitVersion.Tool
# https://github.com/johnkors/dotnet-pr Cmd line tool to open a Pull Request via a browser ex. origin -> GitHub/BitBucket/GitLab/Azure DevOps
dotnet tool install -g dotnet-pr
# https://github.com/tomchavakis/nuget-license
dotnet tool install -g dotnet-project-licenses
# https://github.com/AppCoreNet/SigningTool # A tool for strong-name keys and signing of assemblies.
dotnet tool install --g AppCore.SigningTool
# https://github.com/SonarSource/sonar-scanner-msbuild
dotnet tool install -g dotnet-sonarscanner
# https://github.com/dotnet-campus/dotnetCampus.UpdateAllDotNetTools
dotnet tool install -g dotnetCampus.UpdateAllDotNetTools
# https://github.com/Jon-Indico/DotnetVersion
dotnet tool install -g DotnetVersion
# https://github.com/nil4/dotnet-transform-xdt
dotnet tool install -g dotnet-xdt
# https://github.com/loresoft/EntityFrameworkCore.Generator
dotnet tool install -g EntityFrameworkCore.Generator
# https://github.com/ivanparvaresh/dotnet-exec
dotnet tool install -g dotnet-tool-exec
# https://github.com/hightechict/DashDashVersion Create predictable and opinionated SemVer 2.0.0 version numbers for git flow repositories.
dotnet tool install -g git-flow-version
#nhttps://github.com/bzumhagen/dotnet-gitchanges Generate changelogs from git history.
dotnet tool install -g dotnet-gitchanges
# https://github.com/shaun-h/gti Global tool for installing .Net Global tools from a tools.gti file.
dotnet tool install -g gti
# https://github.com/sebnilsson/DotnetGuid
dotnet tool install -g dotnet-guid
# https://github.com/JosephWoodward/InstallSdkGlobalTool run dotnet install-sdk in a directory that contains global.json
dotnet tool install -g InstallSdkGlobalTool
# https://github.com/onovotny/NuGetKeyVaultSignTool Code sign your .nupkg files using an Authenticode certificate stored in Azure Key Vault
dotnet tool install -g NuGetKeyVaultSignTool
# https://github.com/danielpalme/ReportGenerator/ ReportGenerator converts XML reports generated by OpenCover, PartCover, dotCover, Visual Studio, NCover or Cobertura into human readable reports in various formats.
dotnet tool install -g dotnet-reportgenerator-globaltool
# https://github.com/ekonbenefits/dotnet-ssllabs-check
dotnet tool install -g dotnet-ssllabs-check
# https://github.com/VictorioBerra/TemplateVersions.Tool
dotnet tool install -g TemplateVersions.Tool
# https://github.com/mganss/XmlSchemaClassGenerator Generate XmlSerializer compatible C# classes from XML Schema files.
dotnet tool install -g dotnet-xscgen
# https://github.com/natemcmaster/xunit-cli
dotnet tool install -g xunit-cli


